---
title: "Calculate fidelity metrics"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE}
library(indicspecies)
```

```{r set_filepaths}
# data_path <- file.path("C:", "Users", "zekmar", "OneDrive - UKCEH", "Projects", "MNNPC")
data_path <- file.path("/mnt", "elements")
```

# Read Data

```{r read_data}
plot_data_raw <- read.csv(file = file.path(data_path, "floristic_table_development_data_20251023.csv")) |>
  tibble::as_tibble()

load(file = file.path("./", "data", "mnnpc_community_attributes.rda"))
```

# Prepare Data

```{r tidy_data}
mnnpc_systems <- mnnpc_community_attributes |>
  dplyr::filter(rank == "system")

plot_data_tidy <- plot_data_raw |>
  dplyr::mutate(
    "npc_unit" = dplyr::case_when(
      !is.na(npc_subtype) ~ npc_subtype,
      !is.na(npc_type) ~ npc_type,
      !is.na(npc_class) ~ npc_class,
      TRUE ~ NA
    )
  ) |>
  dplyr::select(Quadrat, Species, Cover, npc_unit) |>
  dplyr::mutate("npc_system" = stringr::str_extract(string = npc_unit, pattern = "^\\w{2}"))

all(sort(unique(mnnpc_systems$npc_code)) == sort(unique(plot_data_tidy$npc_system)))
```

```{r prepare_data}
prepare_data <- function(sys, dat){
  
  # sys <- "AP"
  # dat <- plot_data_tidy
  
  dat <- dat |>
    dplyr::filter(npc_system == sys)
  
  plot_species_wide <- dat |>
    dplyr::select(Quadrat, Species) |>
    dplyr::mutate("present" = 1) |>
    dplyr::arrange(Quadrat) |>
    tidyr::pivot_wider(names_from = Species,
                       values_from = present,
                       values_fill = 0)

  plot_units_vec <- dat |>
    dplyr::distinct(Quadrat, npc_unit) |>
    dplyr::arrange(Quadrat) |>
    tibble::deframe()
  
  plot_units_wide <- dat |>
    dplyr::distinct(Quadrat, npc_unit) |>
    dplyr::arrange(Quadrat) |>
    dplyr::mutate("present" = 1) |>
    tidyr::pivot_wider(names_from = npc_unit,
                       values_from = present)
  
  plot_species_mat <- plot_species_wide |>
    tibble::column_to_rownames("Quadrat") |>
    as.matrix()
  
  plot_units_mat <- plot_units_wide |>
    tibble::column_to_rownames("Quadrat") |>
    as.matrix()
  
  results <- list(
    "plot_species_wide" = plot_species_wide,
    "plot_units_vec" = plot_units_vec,
    "plot_units_wide" = plot_units_wide,
    "plot_species_mat" = plot_species_mat,
    "plot_units_mat" = plot_units_mat
  )
  
  return(results)
  
}

prepped_data_list <- lapply(mnnpc_systems$npc_code, 
                            FUN = prepare_data, 
                            dat = plot_data_tidy)

names(prepped_data_list) <- mnnpc_systems$npc_code
```

# Split by NPC type


# Calculate IndVal data

Asadi, H., Esmailzadeh, O., De Cáceres, M., Hosseini, S.M., 2021. The assignment 
of relevés to pre-existing vegetation units: a comparison of approaches using 
species fidelity. Annals of Forest Science 78, 13. 
https://doi.org/10.1007/s13595-020-01017-0

```{r calc_r}
# calc_r_metric <- function(sys, dat){
#   
#   # sys <- "AP"
#   # dat <- prepped_data_list
#   
#   data <- dat[[sys]][["plot_species_mat"]]
#   clusters <- dat[[sys]][["plot_units_vec"]]
#   r <- indicspecies::multipatt(x = data, cluster = clusters, func = "r.g")
#   
#   r_dat <- r$sign |> 
#     tibble::rownames_to_column(var = "species") |>
#     tibble::as_tibble() |>
#     dplyr::filter(p.value < 0.01) |>
#     dplyr::rename_with(.fn = ~stringr::str_remove(., "^s."), .cols = tidyselect::starts_with("s.")) |>
#     dplyr::select(-index)
#   
#   return(r_dat)
#   
# }
# 
# r_data_list <- lapply(mnnpc_systems$npc_code, 
#                       FUN = calc_r_metric, 
#                       dat = prepped_data_list)
# 
# names(r_data_list) <- mnnpc_systems$npc_code
```

```{r calc_indval}
calc_indval_metric <- function(sys, dat){
  
  # sys <- "AP"
  # dat <- prepped_data_list
  
  data <- dat[[sys]][["plot_species_mat"]]
  clusters <- dat[[sys]][["plot_units_vec"]]
  
  indval <- indicspecies::multipatt(x = data, cluster = clusters, func = "IndVal.g")
  
  indval_dat <- indval$sign |> 
    tibble::rownames_to_column(var = "species") |>
    tibble::as_tibble() |>
    dplyr::filter(p.value < 0.01) |>
    dplyr::rename_with(.fn = ~stringr::str_remove(., "^s."), .cols = tidyselect::starts_with("s.")) |>
    dplyr::select(-index)
  
  print(sys, " completed")
  
  return(indval_dat)
  
}

indval_data_list <- parallel::mclapply(mnnpc_systems$npc_code, 
                                       FUN = calc_indval_metric,
                                       dat = prepped_data_list,
                                       mc.preschedule = FALSE,
                                       mc.cores = 30) 

names(indval_data_list) <- mnnpc_systems$npc_code
```

# Convert r and IndVal to long format

```{r convert_long_format}
indval_data_list_long <- lapply(X = indval_data_list, 
                                FUN = function(X){
                                  
                                  result <- X |>
                                    tidyr::pivot_longer(id_cols = c(species, stat, p.value),
                                                        names_to = "npc_code",
                                                        values_to = "indicator") |>
                                    dplyr::filter(indicator == 1)
                                  
                                  return(result)
                                 
                                })

indval_data_tbl_long <- do.call("rbind", indval_data_list_long)

r_data_list_long <- lapply(X = r_data_list, 
                           FUN = function(X){
                             
                             result <- X |>
                               tidyr::pivot_longer(id_cols = c(species, stat, p.value),
                                                   names_to = "npc_code",
                                                   values_to = "indicator") |>
                               dplyr::filter(indicator == 1)
                             
                             return(result)
                            
                           })

r_data_tbl_long <- do.call("rbind", r_data_list_long)
```

# Write Output Files

```{r write_output_files}
writexl::write_xlsx(x = indval_data_list,
                    path = file.path(data_path, "mnnpc_indval_indicators.xlsx"))

writexl::write_xlsx(x = r_data_list,
                    path = file.path(data_path, "mnnpc_r_indicators.xlsx"))

mnnpc_indval_indicators <- indval_data_tbl_long

usethis::use_data(mnnpc_indval_indicators, internal = FALSE, overwrite = TRUE)
```







